# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Mark Dunne
description:      'Data Scientist working in genetic engineering startup'
url:              http://markdunne.github.io
baseurl:          /

author:
  name:           'Mark Dunne'
  url:            http://markdunne.github.io

# Custom vars
version:          1.0.0
